from setuptools import setup, find_packages

setup(
    name="llmark",
    version="0.1.0",
    author="LLMArk_group",
    description="LLMArk: Multimodal Large Language Model For Flood Risk Assessment",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/LLMArk001/LLMArk",
    packages=find_packages(),
    install_requires=[
        "numpy==1.26.1",
        "open_clip_torch",
        "fastapi",
        "markdown2[all]",
        "numpy",
        "requests",
        "sentencepiece",
        "torch==2.1.2",
        "torchvision==0.16.2",
        "uvicorn",
        "wandb",
        "deepspeed==0.14.2",
        "peft==0.4.0",
        "accelerate>=0.29.1",
        "tokenizers~=0.15.2",
        "bitsandbytes==0.41.0",
        "scikit-learn==1.2.2",
        "sentencepiece~=0.1.99",
        "einops==0.6.1",
        "einops-exts==0.0.4",
        "gradio_client==0.2.9",
        "urllib3<=2.0.0",
        "datasets==2.16.1",
        "pydantic==1.10.8",
        "timm",
        "hf_transfer",
        "opencv-python",
        "av",
        "decord",
        "tyro",
        "scipy",
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: Apache Software License",
    ],
    python_requires=">=3.8",
)